In [20]:
import numpy as np 
import matplotlib.pyplot as plt


In [21]:
x=np.array([[2,3,5],[1,4,6],[7,8,9]])
y=np.array([4,8,12])

theta=(x^T,x)^-1.(x^T,y)


x=x.T,x

y=x.T.y


(x.T,x)^-1


theta=(x^T,x)^-1.(x^T,y)




In [ ]:
# x=np.dot(x.T,x)
# print(x)

[[1034392118 1397689527 1753348575]
 [1397689527 1888587478 2369163690]
 [1753348575 2369163690 2972030201]]


In [ ]:
# y=np.dot(x.T,y)
# print(y)

[36359267588 49129422212 61631066232]


In [ ]:
# X_1=np.linalg.inv(x)
# print(X_1)

[[ 15.93697816 -37.39460118  20.40721301]
 [-37.39460117  87.74409179 -47.88455567]
 [ 20.407213   -47.88455567  26.13210079]]


In [ ]:
# theta=np.dot(X_1,y)
# print(theta)

[ 3.99930054  8.00084151 11.99963612]


DIRECT METHOD FOR NORMAL EQUATION 



theta=(x.t,x)^-1.(x.t,y)


In [19]:
import numpy as np

X = np.array([[2,3,5],[1,4,6],[7,8,9]], dtype=float)
y = np.array([4,8,12], dtype=float).reshape(-1,1)

# Normal equation
theta_closed = np.linalg.inv(X.T @ X) @ (X.T @ y)
# If X.T @ X may be singular, use pseudo-inverse:
theta_pinv = np.linalg.pinv(X) @ y
print("Theta (closed form):\n", theta_closed)
print("Theta (pseudo-inverse):\n", theta_pinv)

Theta (closed form):
 [[-1.28]
 [ 3.52]
 [-0.8 ]]
Theta (pseudo-inverse):
 [[-1.28]
 [ 3.52]
 [-0.8 ]]
